# Cloudflare Pages 配置文件
name = "json-formatter"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "/*", zone_name = "" }
]

[env.preview]
routes = [
  { pattern = "/*", zone_name = "" }
]
